### ISSUE TITLE
Update to latest Cake

### ISSUE THREAD

**Issue by gep13** [enkafan/Cake.Figlet#2]
With the upcoming release of 0.18.0, there is a requirement that all addin's have a minimum version of Cake, i.e. 0.16.2 and above.

@enkafan would you be in a position to update this addin to the latest Cake version, so that it will be supported OOTB?

Thanks!

**Comment by phil-scott-78** [comment]
You bet, I'll get that done here in a bit.

**Comment by gep13** [comment]
Sweet! I recently added Figlet into my Cake.Recipe script, and noticed I would have to remove it due to this.  Thanks for your help!

**Comment by phil-scott-78** [comment]
Ok, pushed up v0.4 of the package that has a minimal version of `0.17`. Nuget is doing its index dance as we speak. 

Glad you found it useful - superfluous ascii art is a must in any build script in my book.

**Comment by gep13** [comment]
>@enkafan said...
superfluous ascii art is a must in any build script in my book

Totally agree. Currently running in on about 15 adding in the cake-control organisation :-)
