### ISSUE TITLE
Would it be possible to use the Cake Contrib Icon for your NuGet Package?

### ISSUE THREAD

**Issue by gep13** [enkafan/Cake.Figlet#3]
Thanks again for creating this Cake Addin, we really appreciate the effort that you have put in to creating it.  

We, the Cake Team, recently announced a new Cake Contrib Icon, details of which can be found here:

http://cakebuild.net/blog/2017/06/new-cake-contrib-icon

Would you consider changing the nuspec file for your NuGet Package to use this new Cake Contrib Icon?  If so, the recommended URL to use is:

https://cdn.rawgit.com/cake-contrib/graphics/a5cf0f881c390650144b2243ae551d5b9f836196/png/cake-contrib-medium.png

Details of the above URL can be found in the repository here:

https://github.com/cake-contrib/graphics

Please let me know if you have any questions.

**Comment by phil-scott-78** [comment]
hey sorry for the super delay here, but was kind of a hiatus. 

But I'm back!

There's a PR by @andymac4182 that also updates the package to use NetStandard. Going to poke at that for a bit and as part of that release I'll include the new icon

**Comment by gep13** [comment]
@enkafan that is great news!  Thanks for getting back to me, and happy to see Cake.Figlet getting upgraded to NetStandard!

**Comment by phil-scott-78** [comment]
holy crap, I finally did it. Sorry for the procrastination, I honestly didn't have anything .NET stack for a while and things snowballed with putting it off. The new release targeting netStandard how the icon so progress has been made.

**Comment by gep13** [comment]
@enkafan woot! Thanks for your help in getting this done!

If this addin isn't going to be on your immediate radar, would you consider moving it into the Cake-Contrib Organisation?  That way, if there is a change required, and you are not in a position to help, other community maintainers would be able to help out as well, but you would still "own" the repository.

**Comment by phil-scott-78** [comment]
I could be talked into it - what's the best way to do that?

**Comment by gep13** [comment]
@enkafan it certainly isn't something that you "have" to do, so please don't feel any sort of pressure.  Just a suggestion to help with the longevity of the project.

The process is detailed here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

Please let me know if you have any questions.

**Comment by phil-scott-78** [comment]
No worries, be proud to transfer this over. Easiest way to transfer to you Gary?

**Comment by gep13** [comment]
@enkafan yip, that would certainly be the easiest way, and I can get you hooked up with the necessary permissions, etc.

**Comment by phil-scott-78** [comment]
cool, transfer request sent

**Comment by gep13** [comment]
@enkafan Nice one! I have moved it into the Cake-Contrib Organisation, and given you the necessary permissions. I have also set up an AppVeyor build for it, and again given you permissions over there.  Let me know if you have any questions, or problems.

Thanks again!
