### ISSUE TITLE
Upgrade to VS2017 and add .NET Core target

### ISSUE THREAD

**Issue by RLittlesII** [enkafan/Cake.Figlet#7]
So addin can be loaded from Cake CoreCLR runner

**Comment by phil-scott-78** [comment]
Hey @RLittlesII, pushed version 1.0 that should work for you. Mind pulling it down and checking it out when you get a chance?

**Comment by RLittlesII** [comment]
@enkafan This is part of a larger effort to get Cake addins running on Cake.CoreCLR.  I looked over your .csproj files and everything seems right for multi target.  I will load up a script and verify that I can get addins on Cake.CoreCLR.

**Comment by gep13** [comment]
@RLittlesII were you able to verify if this is now completed?  Thanks!

**Comment by RLittlesII** [comment]
@gep13 @enkafan Sorry it took me so long to look at this.  Everything appears to be in order.  Thanks!
